// Generated by CoffeeScript 1.9.1
(function() {
  var User,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  require("business-rules-engine");

  User = (function() {
    function User(log, q, timeout) {
      this.log = log;
      this.q = q;
      this.timeout = timeout;
      this.login = bind(this.login, this);
      this.username = "";
      this.password = "";
      this.errors = [];
    }

    User.prototype.login = function() {
      var result;
      result = false;
      this.log.debug("User.login() executing...");
      this.log.debug("username: " + this.username + ", password: " + this.password);
      this.log.debug("User.login() END");
      result = false;
      return result;
    };

    return User;

  })();

  module.exports = User;

}).call(this);
