// Generated by CoffeeScript 1.9.1
(function() {
  var User,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  require("business-rules-engine");

  User = (function() {
    function User(log, q, timeout) {
      this.log = log;
      this.q = q;
      this.timeout = timeout;
      this.login = bind(this.login, this);
      this.username = "";
      this.password = "";
      this.errors = [];
    }

    User.prototype.login = function() {
      var deferred;
      deferred = this.q.defer();
      this.timeout((function(_this) {
        return function() {
          _this.log.debug("deferred.resolve()");
          return deferred.resolve(true);
        };
      })(this), 1);
      return deferred.promise;
    };

    return User;

  })();

  module.exports = User;

}).call(this);
