// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  var LoginController, User;

  User = require("User");

  LoginController = (function() {
    LoginController.factory = [
      "$scope", "$log", "RoutingService", function($scope, $log, RoutingService) {
        var controller;
        controller = new LoginController($scope, $log, RoutingService);
        return controller;
      }
    ];

    function LoginController(scope, log, RoutingService1) {
      this.scope = scope;
      this.log = log;
      this.RoutingService = RoutingService1;
      this.scope.user = new User(this.log);
      this.scope.login = (function(_this) {
        return function() {
          _this.log.debug("scope.login executing...");
          if (_this.scope.user.login()) {
            _this.scope.user.fetch;
            _this.RoutingService.gotoMainScreen();
          } else {
            _this.displayError(_this.scope.user.errors);
          }
          return _this.log.debug("scope.login END");
        };
      })(this);
    }

    LoginController.prototype.displayError = function(errors) {
      this.log.debug("alertify:");
      this.log.debug(alertify);
      alertify.set("notifier", "position", "bottom-right");
      return alertify.error("Please enter your username");
    };

    return LoginController;

  })();

  module.exports = LoginController;

}).call(this);
