// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';

  /*
  browserify-shim dependencies (can be edited in package.json)
   */
  require('angular-ui-bootstrap');

  require('angular-ui-router');


  /*
  app entry point
   */

  require('./app');

}).call(this);
