// Generated by CoffeeScript 1.9.1
(function() {
  var Config;

  Config = (function() {
    Config.factory = [
      "$stateProvider", "$urlRouterProvider", "$logProvider", function($stateProvider, $urlRouterProvider, $logProvider) {
        var config;
        config = new Config($stateProvider, $urlRouterProvider, $logProvider);
        return config.execute();
      }
    ];

    function Config(stateProvider, urlRouterProvider, logProvider) {
      this.stateProvider = stateProvider;
      this.urlRouterProvider = urlRouterProvider;
      this.logProvider = logProvider;
    }

    Config.prototype.execute = function() {
      var logger;
      logger = angular.injector(["ng"]).get("$log");
      logger.debug("config_with_ionic executing...");
      this.logProvider.debugEnabled(true);
      return logger.debug("config_with_ionic END");
    };

    return Config;

  })();

  module.exports = Config;

}).call(this);
