// Generated by CoffeeScript 1.9.1
(function() {
  var app_config, app_module, app_runner;

  app_module = angular.module("dea", ['ui.bootstrap', 'ui.router', 'ionic', require('../../../tmp/templates').name, require('../common').name, require("./login").name]);

  app_runner = require("./run_with_ionic");

  app_config = require("./config_with_ionic");

  app_module.run(app_runner.factory);

  app_module.config(app_config.factory);

}).call(this);
