// Generated by CoffeeScript 1.9.1
(function() {
  var Run;

  Run = (function() {
    Run.factory = [
      "$ionicPlatform", "$log", function($ionicPlatform, $log) {
        var run;
        run = new Run($ionicPlatform, $log);
        return run.execute();
      }
    ];

    function Run(ionicPlatform, log) {
      this.ionicPlatform = ionicPlatform;
      this.log = log;
    }

    Run.prototype.execute = function() {
      this.log.debug("run_with_ionic executing...");
      this.ionicPlatform.ready((function(_this) {
        return function() {
          if (window.cordova && window.cordova.plugins.keyboard) {
            window.cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
          }
          if (window.StatusBar) {
            return window.StatusBar.styleDefault();
          }
        };
      })(this));
      return this.log.debug("run_with_ionic END");
    };

    return Run;

  })();

  module.exports = Run;

}).call(this);
