// Generated by CoffeeScript 1.9.1
(function() {
  var Run, User;

  User = require("../common/domain_models/user");

  Run = (function() {
    Run.factory = [
      "$ionicPlatform", "$log", "$state", function($ionicPlatform, $log, $state) {
        var run;
        run = new Run($ionicPlatform, $log, $state);
        return run.execute();
      }
    ];

    function Run(ionicPlatform, log, state) {
      this.ionicPlatform = ionicPlatform;
      this.log = log;
      this.state = state;
    }

    Run.prototype.execute = function() {
      this.log.debug("run_with_ionic executing...");
      this.ionicPlatform.ready((function(_this) {
        return function() {
          if (window.cordova && window.cordova.plugins.keyboard) {
            window.cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
          }
          if (window.StatusBar) {
            return window.StatusBar.styleDefault();
          }
        };
      })(this));
      if (User.current_user === null) {
        this.state.go("login");
      }
      return this.log.debug("run_with_ionic END");
    };

    return Run;

  })();

  module.exports = Run;

}).call(this);
