// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  var the_module;

  the_module = angular.module("dea.common", [require('./directives').name, require('./filters').name, require('./services').name]);

  module.exports = the_module;

}).call(this);
