// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  var routing_service, the_module;

  the_module = angular.module('dea.common.services', []);

  routing_service = require("./routing_service");

  the_module.factory("RoutingService", routing_service.factory);

  module.exports = the_module;

}).call(this);
