// Generated by IcedCoffeeScript 1.8.0-a
(function() {
  var the_module;

  the_module = angular.module("dea.main_screen", []);

  the_module.config([
    "$stateProvider", function($stateProvider) {
      return $stateProvider.state("main_for_manager", {
        url: "/main",
        templateUrl: "app/main_screen/main_for_manager.html"
      });
    }
  ]);

  module.exports = the_module;

}).call(this);
