// Generated by CoffeeScript 1.9.1
(function() {
  var MainForManagerController;

  MainForManagerController = (function() {
    MainForManagerController.factory = [
      "$scope", "RoutingService", "$log", function($scope, RoutingService, $log) {
        var controller;
        $log.debug("MainForManagerController.factory() executing...");
        controller = new MainForManagerController($scope, RoutingService, $log);
        return controller;
      }
    ];

    function MainForManagerController(scope, RoutingService1, log) {
      this.scope = scope;
      this.RoutingService = RoutingService1;
      this.log = log;
      this.scope.on_tab_new_selected = (function(_this) {
        return function() {
          return _this.RoutingService.gotoListOfNewSCScreen();
        };
      })(this);
      this.scope.on_tab_payment_status_selected = (function(_this) {
        return function() {
          return _this.RoutingService.gotoListOfPaymentStatusScreen();
        };
      })(this);
    }

    return MainForManagerController;

  })();

  module.exports = MainForManagerController;

}).call(this);
